version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=myschooldb
      - MYSQL_ROOT_PASSWORD=notatrickypassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
    ports:
      - '3316:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql:rw,delegated