management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/myschooldb?useTimezone=true?serverTimezone=America/Sao_Paulo
    username: admin
    password: admin1234
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

limits:
  course:
    students:
      max: 50
  student:
    course:
      max: 5


